"""Update columns of problems model

Revision ID: 76952cb9b0ac
Revises: cb9f96a730fa
Create Date: 2023-11-30 16:26:30.177298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76952cb9b0ac'
down_revision: Union[str, None] = 'cb9f96a730fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('approach', sa.String(), nullable=True))
    op.add_column('problems', sa.Column('problem_link', sa.String(), nullable=True))
    op.add_column('problems', sa.Column('solution_link', sa.String(), nullable=True))
    op.drop_column('problems', 'patterns')
    op.drop_column('problems', 'leetcode_import')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('leetcode_import', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('patterns', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('problems', 'solution_link')
    op.drop_column('problems', 'problem_link')
    op.drop_column('problems', 'approach')
    # ### end Alembic commands ###
