"""Update columns of problems and solutions

Revision ID: bdced369f9e3
Revises: 76952cb9b0ac
Create Date: 2023-11-30 16:34:16.821610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdced369f9e3'
down_revision: Union[str, None] = '76952cb9b0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'solution_link')
    op.add_column('solutions', sa.Column('solution_link', sa.String(), nullable=True))
    op.alter_column('solutions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('solutions', 'solution_link')
    op.add_column('problems', sa.Column('solution_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
