"""Remove created and updated

Revision ID: 2f5269006e46
Revises: 955f1f8bb833
Create Date: 2023-11-24 11:37:56.789060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f5269006e46'
down_revision: Union[str, None] = '955f1f8bb833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'updated')
    op.drop_column('problems', 'created')
    op.drop_column('solutions', 'updated')
    op.drop_column('solutions', 'created')
    op.drop_column('tags', 'updated')
    op.drop_column('tags', 'created')
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tags', sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tags', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('solutions', sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('solutions', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
