"""Add created and updated columns to base class

Revision ID: cb9f96a730fa
Revises: 2f5269006e46
Create Date: 2023-11-27 13:53:40.711298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9f96a730fa'
down_revision: Union[str, None] = '2f5269006e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('problems', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('solutions', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('solutions', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tags', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tags', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    op.drop_column('tags', 'updated')
    op.drop_column('tags', 'created')
    op.drop_column('solutions', 'updated')
    op.drop_column('solutions', 'created')
    op.drop_column('problems', 'updated')
    op.drop_column('problems', 'created')
    # ### end Alembic commands ###
